replicaCount: 1
image:
  repository: ghcr.io/iamgeorgezelenkov/m1core-llm-portal
  tag: latest
config:
  airflowUrl: "http://airflow-webserver.airflow.svc.cluster.local:8080"
  airflowUser: "admin"
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"
