apiVersion: v1
kind: Service
metadata:
  name: m1core-llm-portal
  labels:
    app: m1core-llm-portal
spec:
  type: {{ .Values.service.type }}
  selector:
    app: m1core-llm-portal
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
