githubConfigUrl: "https://github.com"
githubConfigSecret: "m1core-runner-gh-token"
runnerScaleSetName: "m1core-k8s-runner"
runnerNamespace: "actions-runner" 

minRunners: 0
maxRunners: 3

containerMode:
  type: "kubernetes"
  kubernetesModeWorkVolumeClaim:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 1Gi
  # ПРАВИЛЬНЫЙ И БЕЗОПАСНЫЙ ПРОБРОС FUSE ДЛЯ BUILDAH:
  # Это автоматически добавит устройство /dev/fuse во все контейнеры задач воркфлоу
  kubernetesModeVolumeMounts:
    - name: dev-fuse
      mountPath: /dev/fuse
      readOnly: false
  # Описание самого ресурса fuse на хосте
  kubernetesModeVolumes:
    - name: dev-fuse
      hostPath:
        path: /dev/fuse

template:
  spec:
    nodeSelector:
      type: heavy
    serviceAccountName: m1core-runner-sa
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        env:
          # Убираем ошибку "Jobs without a job container..."
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"
        # SECURITY-ИСПРАВЛЕНИЕ: Блок securityContext: privileged: true УДАЛЕН.
