githubConfigUrl: "https://github.com/iamgeorgezelenkov/m1core-llm-dags"
githubConfigSecret: "m1core-runner-gh-token"
runnerScaleSetName: "m1core-k8s-runner"
runnerNamespace: "actions-runner"
minRunners: 0
maxRunners: 3

template:
  metadata:
    annotations:
      container.apparmor.security.beta.kubernetes.io/runner: unconfined
  spec:
    nodeSelector:
      type: heavy
    serviceAccountName: m1core-runner-sa
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        env:
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"
        securityContext:
          capabilities:
            add:
              - SYS_ADMIN
          seccompProfile:
            type: Unconfined
