name: Reusable Buildah Build

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      context_dir:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: m1core-k8s-runner
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install buildah
        run: |
          sudo apt-get update
          sudo apt-get install -y buildah

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | buildah login -u "${{ github.actor }}" --password-stdin ghcr.io

      - name: Build Image with Buildah
        run: |
          buildah bud \
            --storage-driver=vfs \
            --isolation=chroot \
            -f ${{ inputs.dockerfile_path }} \
            -t ghcr.io/${{ github.repository_owner }}/${{ inputs.app_name }}:${{ github.sha }} \
            ${{ inputs.context_dir }}

      - name: Push Image to GHCR
        run: |
          buildah push \
            --storage-driver=vfs \
            ghcr.io/${{ github.repository_owner }}/${{ inputs.app_name }}:${{ github.sha }} \
            docker://ghcr.io/${{ github.repository_owner }}/${{ inputs.app_name }}:${{ github.sha }}
