name: Build LLM Portal with Buildah

on:
  push:
    paths:
      - 'apps/m1core-llm-portal/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: m1core-k8s-runner
    permissions:
      contents: read
      packages: write

    # БЛОК container: УДАЛЕН. 
    # Раннер сам знает, что делать, благодаря ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER="false"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Buildah Action
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: m1core-llm-portal
          tags: ${{ github.sha }}
          containerfiles: |
            apps/m1core-llm-portal/Dockerfile
          context: apps/m1core-llm-portal
          # Использование overlay теперь легально и безопасно, 
          # так как /dev/fuse проброшен через kubernetesModeVolumeMounts в Helm
          extra-args: --storage-driver=overlay

      - name: Push Image to GHCR
        uses: redhat-actions/push-to-registry@v1
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
